#!/usr/bin/perl

# Teamspeak 3 Users per channel
# monitor the usage of your TS3 Server channels

use strict;
use Net::Telnet;


my $LOGFILE  = "/var/log/munin/plugin_ts3_channels_current"; 		# watch this file for additional debug output if the script can't poll information from the TS3 server

# TS3 server variables
my $TS3_HOSTNAME = "127.0.0.1";
my $TS3_HOSTPORT = "10011";
my $TS3_QUERYLOGIN = "queryadmin";
my $TS3_QUERYPASSWORD = "SUPERSECRETPASSW0RD";	# replace this example with your valid TS3 queryadmin server password

#################
## telnet part ##
#################

my $telnet = new Net::Telnet ( Timeout=>10, Errmode=>'die', Input_log => $LOGFILE);
$telnet->open(Host => $TS3_HOSTNAME, Port => $TS3_HOSTPORT);
$telnet->waitfor('/Welcome */i');

$telnet->print("login $TS3_QUERYLOGIN $TS3_QUERYPASSWORD");
$telnet->waitfor('/error id=0 msg=ok/i');
$telnet->print('use sid=1');
$telnet->waitfor('/error id=0 msg=ok/i');
$telnet->print("channellist");
my @TELNETRAW = $telnet->waitfor('/error id=0 msg=ok/i');
$telnet->close;

my @channels = split( '\|' , @TELNETRAW[0]);

my $CHANNELID      = "";
my $CHANNELNAME      = "";
my $CHANNELUSERCOUNT = 0;

if ($ARGV[0] and $ARGV[0] eq "autoconf") {
	print "yes\n";
	exit 0;
}

if ($ARGV[0] and $ARGV[0] eq "config") {
	print "graph_args --base 1000 --units=si\n";
	print "graph_vlabel usercount per channel\n";
	print "graph_title TS3 current usage per channel\n";
	print "graph_category teamspeak\n";
	print "graph_info This graph shows the current channel usage.\n";

	foreach my $channel ( @channels )
	{
		my @channelline = split(' ', $channel);
		foreach my $channelpart ( @channelline )
		{
			## process channel_id
			if ($channelpart =~ m/^cid=/)
			{
				# remove "cid=" from cid=42 
				my @TMPCHANNELID = split("=", $channelpart);
				$CHANNELID = @TMPCHANNELID[1]
			}
                        
			## process client_nickname
			if ($channelpart =~ m/^channel_name=/)
			{
				# remove trailing channel_name= from string
				my @TMPCHANNELNAME = split("=", $channelpart);
				$CHANNELNAME = @TMPCHANNELNAME[1];
				## clean CHANNELNAME from non-ascii as mysql database transforms into a blackhole and destroys earth if we feed it with unicode
				$CHANNELNAME =~ s/[^a-zA-Z0-9_-]/_/g;
			}
		}
		$CHANNELID = sprintf("%04d", $CHANNELID);	# 
		print ($CHANNELID.".label cid".$CHANNELID."_".$CHANNELNAME."\n");
	}
	exit 0;
}


foreach my $channel ( @channels )
{
	my @channelline = split(' ', $channel);
	foreach my $channelpart ( @channelline )
	{
		## process channel_id
		if ($channelpart =~ m/^cid=/)
		{
			# remove "cid=" from cid=42 
			my @TMPCHANNELID = split("=", $channelpart);
			$CHANNELID = @TMPCHANNELID[1]
		}
                       
		## process usercount per channel
		if ($channelpart =~ m/^total_clients=/)
		{
			# remove trailing channel_name= from string
			my @TMPCHANNELUC = split("=", $channelpart);
			$CHANNELUSERCOUNT = @TMPCHANNELUC[1];
	
			if($CHANNELID == 1)     # subtract 1 for query client as query client joins default channel
			{
				$CHANNELUSERCOUNT -= 1;
			}
		}
	}
	$CHANNELID = sprintf("%04d", $CHANNELID);	# 
	print ($CHANNELID.".value ".$CHANNELUSERCOUNT."\n");
}
                


               
